### ISSUE TITLE
Make Trade History

### ISSUE THREAD

**Issue by Young-in** [Young-in/Stock-Trading-Bot#6]
Make a data structure for the trade history.
It will represent how the bot trades.
It will be used to save the actions of arbitrary strategies and evaluate the score of those.

**Comment by Kang-Min-Ku** [comment]
Data Feature for trade history.

event_time | item_code | name | price | total_price | fee | remain

ex) 2021/01/05 11:03:40 | 005930 | 삼성전자 | 89400 | 10 | 894000 | 100000000

**Comment by Kang-Min-Ku** [comment]
I have a issue about expressing date. There are two options to save date.

First one is naive datetime. It doesn't contain time zone information. It just expresses time.
e.g. datetime.datetime(2021, 1, 30, 4, 58, 4, 114979)

Second one is aware datetime. It contains time zone information.
e.g.datetime.datetime(2019, 2, 15, 4, 58, 4, 114979, tzinfo="Asia/Seoul")) 

If we treat not only KOSPI or KOSDAQ, but also foreign market, aware datetime will help us.


<Reference>
https://spoqa.github.io/2019/02/15/python-timezone.html

**Comment by Kang-Min-Ku** [comment]
Complete trade history.

**Comment by Kang-Min-Ku** [comment]
Complete trade history.

**Issue & Enhancement**
1. Crawling speed is too slow. We need some ways to enhance crawling speed
2. updateStatus func in history class is private now.  I think It's not good that much.
3. checkData func enhancement.
4. Enhance isBuyable and isSellable
5. When program is started, create /data/history directory if there is no /data/history directory.
6. Make function trades multiple stocks at the same time.

**Next Plan**
1. Enhance crawling speed and connection stability.
2. Make virtual trade
3. Make investment strategy
4. Evaluate trades

**Comment by Kang-Min-Ku** [comment]
<My Next Plan>
1. Enhance crawling speed and connection stability.
2. Make virtual trade
3. Make investment strategy
4. Evaluate trades
